[project]
name = "mazeman"
version = "0.1.0"
description = "A simple maze game to reminisce about 1999"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pygame>=2.6.1",
]

[project.scripts]
"mazeman" = "mazeman:main"

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"